class Meal1 {
  int? id;
  String? name;
  String? detalis;
  String? imageUrl;
  String? cost;
  String? type;
  String? time;
  String? kkal;
  int? bannerColor;
  int? ingCount;

  Meal1({this.id, this.name,this.detalis,  this.imageUrl, this.cost, this.type, this.time, this.kkal , this.bannerColor, this.ingCount});

  static List<Meal1> mealsUz = [
    Meal1(
        id: 1,
        name: "Jiz",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/jiz.png",
        cost: "40 000",
        type: "Ovqatlar-II",
        time: "20 min",
        kkal: "145 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal1(
        id: 2,
        name: "Qozon kabob",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/qozon.png",
        cost: "40 000",
        type: "Ovqat-II",
        time: "20 мин",
        kkal: "154 кал",
        bannerColor: 0xffDCC7B1,
        ingCount: 7),
    Meal1(
        id: 3,
        name: "Norin",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/norin.png",
        cost: "28 000",
        type: "Ovqatlar-II",
        time: "15 мин",
        kkal: "125",
        bannerColor: 0xffFFC5A8,
        ingCount: 9),
    Meal1(
        id: 4,
        name: "Tushonka",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/tushonka.png",
        cost: "40 000",
        type: "Ovqatlar-II",
        time: "15 min",
        kkal: "158 kkal",
        bannerColor: 0xff71C3A1,
        ingCount: 8),
    Meal1(
        id: 5,
        name: "Telyatina",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/telyatina.png",
        cost: "40 000",
        type: "Ovqatlar-II",
        time: "20 мин",
        kkal: "438 кал",
        bannerColor: 0xffA8B6FF,
        ingCount: 6),
    Meal1(
        id: 6,
        name: "Dapanji",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/dapanji.png",
        cost: "35 000",
        type: "Ovqatlar-II",
        time: "15 мин",
        kkal: "438 кал",
        bannerColor: 0xffFFE7A8,
        ingCount: 7),
    Meal1(
        id: 7,
        name: "Jo'Ja (tandir)",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/joja.png",
        cost: "55 000",
        type: "Ovqatlar-II",
        time: "15 min",
        kkal: "438 кал",
        bannerColor: 0xffCEA8FF,
        ingCount: 11),
    Meal1(
        id: 8,
        name: "Jo'ja (oddiy)",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/joja.png",
        cost: "60 000",
        type: "Ovqatlar-II",
        time: "15 min",
        kkal: "438 кал",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal1(
        id: 9,
        name: "Baliq",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/baliq1.png",
        cost: "80 000",
        type: "Ovqatlar-II",
        time: "15 min",
        kkal: "438 кал",
        bannerColor: 0xffFFA8A8,
        ingCount: 8),
    Meal1(
        id: 10,
        name: "Kartoshka Fri",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/fri.png",
        cost: "10 000",
        type: "Ovqatlar-II",
        time: "15 min",
        kkal: "438 кал",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal1(
        id: 11,
        name: "Besh Barmoq",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/dishes/beshbarmoq.png",
        cost: "30 000",
        type: "Ovqatlat-II",
        time: "15 min",
        kkal: "438 кал",
        bannerColor: 0xffDCC7B1,
        ingCount: 11),

  ];

  static List<Meal1> mealsRu = [
    Meal1(
        id: 1,
        name: "Джиз",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/jiz.png",
        cost: "40 000",
        type: "Блюда-II",
        time: "20 мин",
        kkal: "145 кал",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal1(
        id: 2,
        name: "Қозон кабоб ",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/qozon.png",
        cost: "40 000",
        type: "Блюда-II",
        time: "20 min",
        kkal: "154 ккал",
        bannerColor: 0xffDCC7B1,
        ingCount: 7),
    Meal1(
        id: 3,
        name: "Норин",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/norin.png",
        cost: "28 000",
        type: "Блюда-II",
        time: "15 мин",
        kkal: "125 ккал",
        bannerColor: 0xffFFC5A8,
        ingCount: 9),
    Meal1(
        id: 4,
        name: "Тушонка",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/tushonka.png",
        cost: "40 000",
        type: "Блюда-II",
        time: "15 мин",
        kkal: "158 ккал",
        bannerColor: 0xff71C3A1,
        ingCount: 8),
    Meal1(
        id: 5,
        name: "Телятина",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/telyatina.png",
        cost: "40 000",
        type: "Блюда-II",
        time: "15 мин",
        kkal: "438 кал",
        bannerColor: 0xffA8B6FF,
        ingCount: 6),
    Meal1(
        id: 6,
        name: "Дапанжи",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/dapanji.png",
        cost: "16 000",
        type: "Блюда-II",
        time: "5 мин",
        kkal: "438 кал",
        bannerColor: 0xffFFE7A8,
        ingCount: 7),
    Meal1(
        id: 7,
        name: "ЖўЖа (тандир)",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/joja.png",
        cost: "30 000",
        type: "Блюда-II",
        time: "12 мин",
        kkal: "438 кал",
        bannerColor: 0xffCEA8FF,
        ingCount: 11),
    Meal1(
        id: 8,
        name: "Жўжа (оддий)",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/joja.png",
        cost: "30 000",
        type: "Блюда-II",
        time: "14 мин",
        kkal: "438 кал",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal1(
        id: 9,
        name: "Балик",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/baliq1.png",
        cost: "30 000",
        type: "Блюда-II",
        time: "11 мин",
        kkal: "438 кал",
        bannerColor: 0xffFFA8A8,
        ingCount: 8),
    Meal1(
        id: 10,
        name: "Картошка Фри",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/fri.png",
        cost: "30 000",
        type: "Кавказская",
        time: "15 мин",
        kkal: "438 кал",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal1(
        id: 11,
        name: "Беш Бармок",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/beshbarmoq.png",
        cost: "30 000",
        type: "Блюда-II",
        time: "12 мин",
        kkal: "438 кал",
        bannerColor: 0xffDCC7B1,
        ingCount: 11),


  ];

  static List<Meal1> mealsEn = [
    Meal1(
        id: 1,
        name: "Jiz",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/jiz.png",
        cost: "40 000",
        type: "Кавказская",
        time: "20 min",
        kkal: "145 кал",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal1(
        id: 2,
        name: "Qozon kabob",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/qozon.png",
        cost: "40 000",
        type: "Meals-II",
        time: "20 min",
        kkal: "154 kkal",
        bannerColor: 0xffDCC7B1,
        ingCount: 7),
    Meal1(
        id: 3,
        name: "Norin",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/norin.png",
        cost: "25 000",
        type: "Meals-II",
        time: "15 min",
        kkal: "125 kkal",
        bannerColor: 0xffFFC5A8,
        ingCount: 9),
    Meal1(
        id: 4,
        name: "Tushonka",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/tushonka.png",
        cost: "40 000",
        type: "Meals-II",
        time: "15 min",
        kkal: "158 kkal",
        bannerColor: 0xff71C3A1,
        ingCount: 8),
    Meal1(
        id: 5,
        name: "Telyatina",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/telyatina.png",
        cost: "40 000",
        type: "Meals-II",
        time: "15 мин",
        kkal: "438 кал",
        bannerColor: 0xffA8B6FF,
        ingCount: 6),
    Meal1(
        id: 6,
        name: "Dapanji",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/dapanji.png",
        cost: "16 000",
        type: "Meals-II",
        time: "5 мин",
        kkal: "438 кал",
        bannerColor: 0xffFFE7A8,
        ingCount: 7),
    Meal1(
        id: 7,
        name: "Jo'Ja (tandir)",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/joja.png",
        cost: "30 000",
        type: "Meals-II",
        time: "12 мин",
        kkal: "438 кал",
        bannerColor: 0xffCEA8FF,
        ingCount: 11),
    Meal1(
        id: 8,
        name: "Jo'ja (oddiy)",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/joja.png",
        cost: "30 000",
        type: "Meals-II",
        time: "14 мин",
        kkal: "438 кал",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal1(
        id: 9,
        name: "Baliq",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/baliq1.png",
        cost: "30 000",
        type: "Meals-II",
        time: "11 мин",
        kkal: "438 кал",
        bannerColor: 0xffFFA8A8,
        ingCount: 8),
    Meal1(
        id: 10,
        name: "Kartoshka Fri",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/fri.png",
        cost: "30 000",
        type: "Meals-II",
        time: "15 мин",
        kkal: "438 кал",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal1(
        id: 11,
        name: "Besh Barmoq",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/beshbarmoq.png",
        cost: "30 000",
        type: "Meals-II",
        time: "12 мин",
        kkal: "438 кал",
        bannerColor: 0xffDCC7B1,
        ingCount: 11),


  ];
}
