class Meal {
  int? id;
  String? name;
  String? detalis;
  String? imageUrl;
  String? cost;
  String? type;
  String? time;
  String? kkal;
  int? bannerColor;
  int? ingCount;

  Meal({this.id, this.name,this.detalis,  this.imageUrl, this.cost, this.type, this.time, this.kkal , this.bannerColor, this.ingCount});

  static List<Meal> mealsUz = [
    Meal(
        id: 1,
        name: "Qiyma",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik2.png",
        cost: "14 000",
        type: "Shashliklar",
        time: "15 min",
        kkal: "220 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 5),
    Meal(
        id: 2,
        name: "Tovuq filesi ",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/tovuq1.png",
        cost: "20 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "198 kkal",
        bannerColor: 0xffDCC7B1,
        ingCount: 7),
    Meal(
        id: 3,
        name: "Navro'z",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik1.png",
        cost: "22 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "235 kkal",
        bannerColor: 0xffFFC5A8,
        ingCount: 9),
    Meal(
        id: 4,
        name: "O'rama qiyma",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik9.png",
        cost: "20 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "245 kkal",
        bannerColor: 0xff71C3A1,
        ingCount: 8),
    Meal(
        id: 5,
        name: "Kavkaz mol",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik7.png",
        cost: "35 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "268 kkal",
        bannerColor: 0xffA8B6FF,
        ingCount: 6),
    Meal(
        id: 6,
        name: "Kavkaz qo'y",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik7.png",
        cost: "35 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "285 kkal",
        bannerColor: 0xffFFE7A8,
        ingCount: 7),
    Meal(
        id: 7,
        name: "Kavkaz fele",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik4.png",
        cost: "40 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "286 kkal",
        bannerColor: 0xffCEA8FF,
        ingCount: 8),
    Meal(
        id: 8,
        name: "Dollar",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik3.png",
        cost: "37 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "282 kkal",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal(
        id: 9,
        name: "Napaleon",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik6.png",
        cost: "22 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "264 kkal",
        bannerColor: 0xffFFA8A8,
        ingCount: 8),
    Meal(
        id: 10,
        name: "Qiyma kavkaz",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik7.png",
        cost: "30 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "256 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal(
        id: 11,
        name: "Baxor",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/shashlik/shashlik3.png",
        cost: "20 000",
        type: "Shashliklar",
        time: "10 min",
        kkal: "254 kkal",
        bannerColor: 0xffDCC7B1,
        ingCount: 6),


  ];

  static List<Meal> mealsRu = [
    Meal(
        id: 1,
        name: "Кийма",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik2.png",
        cost: "14 000",
        type: "Шашлыки",
        time: "15 мин",
        kkal: "220 ккал",
        bannerColor: 0xffF2DFE1,
        ingCount: 5),
    Meal(
        id: 2,
        name: "Курине филе",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/tovuq1.png",
        cost: "20 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "198 ккал",
        bannerColor: 0xffDCC7B1,
        ingCount: 7),
    Meal(
        id: 3,
        name: "Навруз",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik1.png",
        cost: "22 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "235 ккал",
        bannerColor: 0xffFFC5A8,
        ingCount: 9),
    Meal(
        id: 4,
        name: "Кийма рулет",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik9.png",
        cost: "20 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "245 кал",
        bannerColor: 0xff71C3A1,
        ingCount: 8),
    Meal(
        id: 5,
        name: "Кавказ мол",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik7.png",
        cost: "35 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "268 кал",
        bannerColor: 0xffA8B6FF,
        ingCount: 6),
    Meal(
        id: 6,
        name: "Кавказ Кўй",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik7.png",
        cost: "35 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "285 кал",
        bannerColor: 0xffFFE7A8,
        ingCount: 7),
    Meal(
        id: 7,
        name: "Кавказская феле",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik4.png",
        cost: "40 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "286 кал",
        bannerColor: 0xffCEA8FF,
        ingCount: 8),
    Meal(
        id: 8,
        name: "Доллар",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik3.png",
        cost: "37 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "282 кал",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal(
        id: 9,
        name: "Наполеон",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik6.png",
        cost: "22 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "264 кал",
        bannerColor: 0xffFFA8A8,
        ingCount: 8),
    Meal(
        id: 10,
        name: "Фарш Кавказский",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik7.png",
        cost: "30 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "256 кал",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal(
        id: 11,
        name: "Бахор",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/shashlik/shashlik3.png",
        cost: "20 000",
        type: "Шашлыки",
        time: "10 мин",
        kkal: "254 кал",
        bannerColor: 0xffDCC7B1,
        ingCount: 6),


  ];

  static List<Meal> mealsEn = [
    Meal(
        id: 1,
        name: "Qiyma",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik2.png",
        cost: "14 000",
        type: "Shashliks",
        time: "15 min",
        kkal: "220 kkal ",
        bannerColor: 0xffF2DFE1,
        ingCount: 5),
    Meal(
        id: 2,
        name: "Chicken fillet",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/tovuq1.png",
        cost: "20 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "198 kkal",
        bannerColor: 0xffDCC7B1,
        ingCount: 7),
    Meal(
        id: 3,
        name: "Navruz",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik1.png",
        cost: "22 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "235 kkal",
        bannerColor: 0xffFFC5A8,
        ingCount: 9),
    Meal(
        id: 4,
        name: "Qiyma o'rama",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik9.png",
        cost: "20 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "245 kkal",
        bannerColor: 0xff71C3A1,
        ingCount: 8),
    Meal(
        id: 5,
        name: "Kavkaz mol",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik7.png",
        cost: "35 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "268 kkal",
        bannerColor: 0xffA8B6FF,
        ingCount: 6),
    Meal(
        id: 6,
        name: "Шашлык 6",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik7.png",
        cost: "35 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "285 kkal",
        bannerColor: 0xffFFE7A8,
        ingCount: 7),
    Meal(
        id: 7,
        name: "Kavkaz fele",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik4.png",
        cost: "40 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "286 kkal",
        bannerColor: 0xffCEA8FF,
        ingCount: 8),
    Meal(
        id: 8,
        name: "Dollar",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik3.png",
        cost: "35 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "282 kkal",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal(
        id: 9,
        name: "Napaleon",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik6.png",
        cost: "22 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "264 kkal",
        bannerColor: 0xffFFA8A8,
        ingCount: 8),
    Meal(
        id: 10,
        name: "Qiyma kavkaz",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik7.png",
        cost: "30 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "256 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal(
        id: 11,
        name: "Baxor",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/shashlik/shashlik3.png",
        cost: "20 000",
        type: "Shashliks",
        time: "10 min",
        kkal: "254 кал",
        bannerColor: 0xffDCC7B1,
        ingCount: 6),

  ];
}
