class Meal {
  int? id;
  String? name;
  String? detalis;
  String? imageUrl;
  String? cost;
  String? type;
  String? time;
  String? kkal;
  int? bannerColor;
  int? ingCount;

  Meal({this.id, this.name,this.detalis,  this.imageUrl, this.cost, this.type, this.time, this.kkal , this.bannerColor, this.ingCount});

  static List<Meal> mealsUz = [
    Meal(
        id: 1,
        name: "Мужской каприз",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/mujiskiyKapriz.png",
        cost: "26 000",
        type: "Salatlar",
        time: "10 min",
        kkal: "120 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 5),
    Meal(
        id: 2,
        name: "Грибной",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/grubnoy.png",
        cost: "26 000",
        type: "Salatlar",
        time: "8 мин",
        kkal: "135 kkal",
        bannerColor: 0xffDCC7B1,
        ingCount: 7),
    Meal(
        id: 3,
        name: "Хе мясной",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/xe.png",
        cost: "26 000",
        type: "Salatlar",
        time: "10 min",
        kkal: "126 kkal",
        bannerColor: 0xffFFC5A8,
        ingCount: 9),
    Meal(
        id: 4,
        name: "Мимоза",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/mimoza.png",
        cost: "26 000",
        type: "Salatlar",
        time: "10 min",
        kkal: "132 kkal",
        bannerColor: 0xff71C3A1,
        ingCount: 8),
    Meal(
        id: 5,
        name: "Немецкий",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/nemiskiy.png",
        cost: "26 000",
        type: "Salatlar",
        time: "15 min",
        kkal: "150 kkal",
        bannerColor: 0xffA8B6FF,
        ingCount: 6),
    Meal(
        id: 6,
        name: "Пикантный",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/pikantniy.png",
        cost: "26 000",
        type: "Salatlar",
        time: "10 min",
        kkal: "148 kkal",
        bannerColor: 0xffFFE7A8,
        ingCount: 7),
    Meal(
        id: 7,
        name: "Огурцы с мясом",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/bodiring.png",
        cost: "25 000",
        type: "Salatlar",
        time: "12 min",
        kkal: "154 kkal",
        bannerColor: 0xffCEA8FF,
        ingCount: 6),
    Meal(
        id: 8,
        name: "Паприка",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/paprika.png",
        cost: "25 000",
        type: "Salatlar",
        time: "10 min",
        kkal: "125 kkal",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal(
        id: 9,
        name: "Бабарский",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/babariskiy.png",
        cost: "25 000",
        type: "Salatlar",
        time: "14 min",
        kkal: "165 kkal",
        bannerColor: 0xffFFA8A8,
        ingCount: 8),
    Meal(
        id: 10,
        name: "Смак",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/smak.png",
        cost: "25 000",
        type: "Salatlar",
        time: "15 min",
        kkal: "145 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal(
        id: 11,
        name: "Версал",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi",
        imageUrl: "assets/salads/versal.png",
        cost: "25 000",
        type: "Salatlar",
        time: "12 min",
        kkal: "165 кал",
        bannerColor: 0xffDCC7B1,
        ingCount: 8),


  ];

  static List<Meal> mealsRu = [
    Meal(
        id: 1,
        name: "Мужской каприз",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/mujiskiyKapriz.png",
        cost: "26 000",
        type: "Салаты",
        time: "10 мин",
        kkal: "120 ккал",
        bannerColor: 0xffF2DFE1,
        ingCount: 5),
    Meal(
        id: 2,
        name: "Грибной",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/grubnoy.png",
        cost: "26 000",
        type: "Салаты",
        time: "8 мин",
        kkal: "135 ккал",
        bannerColor: 0xffDCC7B1,
        ingCount: 7),
    Meal(
        id: 3,
        name: "Хе мясной",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/xe.png",
        cost: "26 000",
        type: "Салаты",
        time: "10 мин",
        kkal: "126 ккал",
        bannerColor: 0xffFFC5A8,
        ingCount: 9),
    Meal(
        id: 4,
        name: "Мимоза",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/mimoza.png",
        cost: "26 000",
        type: "Салаты",
        time: "10 мин",
        kkal: "132 ккал",
        bannerColor: 0xff71C3A1,
        ingCount: 8),
    Meal(
        id: 5,
        name: "Немецкий",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/nemiskiy.png",
        cost: "26 000",
        type: "Салаты",
        time: "15 мин",
        kkal: "150 ккал",
        bannerColor: 0xffA8B6FF,
        ingCount: 6),
    Meal(
        id: 6,
        name: "Пикантный",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/pikantniy.png",
        cost: "26 000",
        type: "Салаты",
        time: "10 мин",
        kkal: "148 ккал",
        bannerColor: 0xffFFE7A8,
        ingCount: 7),
    Meal(
        id: 7,
        name: "Огурцы с мясом",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/bodiring.png",
        cost: "25 000",
        type: "Салаты",
        time: "12 мин",
        kkal: "154 ккал",
        bannerColor: 0xffCEA8FF,
        ingCount: 6),
    Meal(
        id: 8,
        name: "Паприка",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/paprika.png",
        cost: "25 000",
        type: "Салаты",
        time: "10 мин",
        kkal: "125 ккал",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal(
        id: 9,
        name: "Бабарский",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/babariskiy.png",
        cost: "25 000",
        type: "Салаты",
        time: "14 мин",
        kkal: "165 ккал",
        bannerColor: 0xffFFA8A8,
        ingCount: 8),
    Meal(
        id: 10,
        name: "Смак",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/smak.png",
        cost: "25 000",
        type: "Салаты",
        time: "15 мин",
        kkal: "145 ккал",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal(
        id: 11,
        name: "Версал",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/salads/versal.png",
        cost: "25 000",
        type: "Салаты",
        time: "12 мин",
        kkal: "165 ккал",
        bannerColor: 0xffDCC7B1,
        ingCount: 8),


  ];

  static List<Meal> mealsEn = [
    Meal(
        id: 1,
        name: "Мужской каприз",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/mujiskiyKapriz.png",
        cost: "26 000",
        type: "Salads",
        time: "10 min",
        kkal: "120 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 5),
    Meal(
        id: 2,
        name: "Грибной",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/grubnoy.png",
        cost: "26 000",
        type: "Salads",
        time: "8 мин",
        kkal: "135 kkal",
        bannerColor: 0xffDCC7B1,
        ingCount: 7),
    Meal(
        id: 3,
        name: "Хе мясной",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/xe.png",
        cost: "26 000",
        type: "Salads",
        time: "10 min",
        kkal: "126 kkal",
        bannerColor: 0xffFFC5A8,
        ingCount: 9),
    Meal(
        id: 4,
        name: "Мимоза",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/mimoza.png",
        cost: "16 000",
        type: "Salads",
        time: "10 мин",
        kkal: "132 kkal",
        bannerColor: 0xff71C3A1,
        ingCount: 8),
    Meal(
        id: 5,
        name: "Немецкий",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/nemiskiy.png",
        cost: "26 000",
        type: "Salads",
        time: "15 min",
        kkal: "150 kkal",
        bannerColor: 0xffA8B6FF,
        ingCount: 6),
    Meal(
        id: 6,
        name: "Пикантный",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/pikantniy.png",
        cost: "26 000",
        type: "Salads",
        time: "10 min",
        kkal: "148 kkal",
        bannerColor: 0xffFFE7A8,
        ingCount: 7),
    Meal(
        id: 7,
        name: "Огурцы с мясом",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/bodiring.png",
        cost: "25 000",
        type: "Salads",
        time: "12 min",
        kkal: "154 kkal",
        bannerColor: 0xffCEA8FF,
        ingCount: 6),
    Meal(
        id: 8,
        name: "Паприка",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/paprika.png",
        cost: "25 000",
        type: "Salads",
        time: "10 min",
        kkal: "125 kkal",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal(
        id: 9,
        name: "Бабарский",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/babariskiy.png",
        cost: "25 000",
        type: "Salads",
        time: "14 min",
        kkal: "165 kkal",
        bannerColor: 0xffFFA8A8,
        ingCount: 8),
    Meal(
        id: 10,
        name: "Смак",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/smak.png",
        cost: "25 000",
        type: "Salads",
        time: "15 мин",
        kkal: "145 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 6),
    Meal(
        id: 11,
        name: "Версал",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/salads/versal.png",
        cost: "25 000",
        type: "Salads",
        time: "12 min",
        kkal: "165 kkal",
        bannerColor: 0xffDCC7B1,
        ingCount: 8),


  ];
}
