class Meal {
  int? id;
  String? name;
  String? detalis;
  String? imageUrl;
  String? cost;
  String? type;
  String? time;
  String? kkal;
  int? bannerColor;
  int? ingCount;

  Meal({this.id, this.name,this.detalis,  this.imageUrl, this.cost, this.type, this.time, this.kkal , this.bannerColor, this.ingCount});

  static List<Meal> mealsUz = [
    Meal(
        id: 1,
        name: "Sho'rva mol go'shti",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/shorva_1.png",
        cost: "25 000",
        type: "Ovqatlar-I",
        time: "20 min",
        kkal: "63 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 11),
    Meal(
        id: 2,
        name: "Sho'rva qo'y  go'shti",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/shorva_3.png",
        cost: "25 000",
        type: "Ovqatlar-I",
        time: "20 min",
        kkal: "85 kkal",
        bannerColor: 0xffDCC7B1,
        ingCount: 12),
    Meal(
        id: 3,
        name: "Dum sho'rva",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/shorva_2.png",
        cost: "25 000",
        type: "Ovqatlar-I",
        time: "20 min",
        kkal: "78 kkal",
        bannerColor: 0xffFFC5A8,
        ingCount: 12),
    Meal(
        id: 4,
        name: "Mastava",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/mastava.png",
        cost: "18 000",
        type: "Ovqatlar-I",
        time: "15 min",
        kkal: "65 kkal",
        bannerColor: 0xff71C3A1,
        ingCount: 15),
    Meal(
        id: 5,
        name: "Borsh",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/borsh.png",
        cost: "20 000",
        type: "Ovqatlai-I",
        time: "15 min",
        kkal: "75 kkal",
        bannerColor: 0xffA8B6FF,
        ingCount: 13),
    Meal(
        id: 6,
        name: "Solyanka",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/solyonka.png",
        cost: "25 000",
        type: "Ovqatlai-I",
        time: "15 min",
        kkal: "78",
        bannerColor: 0xffFFE7A8,
        ingCount: 10),
    Meal(
        id: 7,
        name: "Pelmen",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/pilmen.png",
        cost: "20 000",
        type: "Ovqatlai-I",
        time: "15 min",
        kkal: "95 kkal",
        bannerColor: 0xffCEA8FF,
        ingCount: 6),
    Meal(
        id: 8,
        name: "Tovuq lapsha",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/lapsha.png",
        cost: "16 000",
        type: "Ovqatlai-I",
        time: "15 min",
        kkal: "75 kkal",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal(
        id: 9,
        name: "Teftel",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/teftel.png",
        cost: "25 000",
        type: "Ovqatlai-I",
        time: "15 min",
        kkal: "85 kkal",
        bannerColor: 0xffFFA8A8,
        ingCount: 15),
    Meal(
        id: 10,
        name: "Turkcha ",
        detalis: "Ovqat shinavandalari turli hil mazali taomlarga boy menyuni shubhasiz yuqori baholaydilar.Oshxonada qat’iy sifat nazorati ta’minlanadi – faqat ishonchli hamkorlardan olinadigan sof mahsulotlar, aynan shunday yondashuv oshpazlikning asl betakror asarlarni yaratish imkoniyatini beradi.",
        imageUrl: "assets/dishes/turechiski.png",
        cost: "25 000",
        type: "Ovqatlai-I",
        time: "15 min",
        kkal: "85 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 9),


  ];

  static List<Meal> mealsRu = [
    Meal(
        id: 1,
        name: "Шўрва мол гўшти",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/shorva_1.png",
        cost: "25 000",
        type: "Блюда-I",
        time: "20 мин",
        kkal: "63 кал",
        bannerColor: 0xffF2DFE1,
        ingCount: 11),
    Meal(
        id: 2,
        name: "Шўрва кўй гўшти ",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/shorva_3.png",
        cost: "25 000",
        type: "Блюда-I",
        time: "20 мин",
        kkal: "85 ккал",
        bannerColor: 0xffDCC7B1,
        ingCount: 12),
    Meal(
        id: 3,
        name: "Дум шўрва",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/shorva_2.png",
        cost: "25 000",
        type: "Блюда-I",
        time: "20 мин",
        kkal: "78 ккал",
        bannerColor: 0xffFFC5A8,
        ingCount: 12),
    Meal(
        id: 4,
        name: "Мастава",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/mastava.png",
        cost: "18 000",
        type: "Блюда-I",
        time: "15 мин",
        kkal: "65 ккал",
        bannerColor: 0xff71C3A1,
        ingCount: 15),
    Meal(
        id: 5,
        name: "Борщ",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/borsh.png",
        cost: "20 000",
        type: "Блюда-I",
        time: "15 мин",
        kkal: "75 ккал",
        bannerColor: 0xffA8B6FF,
        ingCount: 13),
    Meal(
        id: 6,
        name: "Солянка",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/solyonka.png",
        cost: "25 000",
        type: "Блюда-I",
        time: "15 мин",
        kkal: "78 ккал",
        bannerColor: 0xffFFE7A8,
        ingCount: 10),
    Meal(
        id: 7,
        name: "Пельмени",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/pilmen.png",
        cost: "20 000",
        type: "Блюда-I",
        time: "15 мин",
        kkal: "95 ккал",
        bannerColor: 0xffCEA8FF,
        ingCount: 6),
    Meal(
        id: 8,
        name: "Куриная лапша",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/lapsha.png",
        cost: "16 000",
        type: "Блюда-I",
        time: "15 мин",
        kkal: "75 ккал",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal(
        id: 9,
        name: "Тефтель",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/teftel.png",
        cost: "25 000",
        type: "Блюда-I",
        time: "15 мин",
        kkal: "85 ккал",
        bannerColor: 0xffFFA8A8,
        ingCount: 15),
    Meal(
        id: 10,
        name: "Tурецки",
        detalis: "Гурманы по достоинству оценят меню, включающее богатый ассортимент блюд.На кухне поддерживается строгий контроль качества – только свежие продукты от проверенных партнеров, ведь именно такой подход позволяет создавать настоящие шедевры.",
        imageUrl: "assets/dishes/turechiski.png",
        cost: "25 000",
        type: "Блюда-I",
        time: "15 мин",
        kkal: "85 ккал",
        bannerColor: 0xffF2DFE1,
        ingCount: 9),


  ];

  static List<Meal> mealsEn = [
    Meal(
        id: 1,
        name: "Sho'rva mol go'shti",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/shorva_1.png",
        cost: "25 000",
        type: "Meals-I",
        time: "20 min",
        kkal: "63 кал",
        bannerColor: 0xffF2DFE1,
        ingCount: 11),
    Meal(
        id: 2,
        name: "Sho'rva qo'y  go'shti",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/shorva_3.png",
        cost: "25 000",
        type: "Meals-I",
        time: "20 min",
        kkal: "85 kkal",
        bannerColor: 0xffDCC7B1,
        ingCount: 12),
    Meal(
        id: 3,
        name: "Dum sho'rva",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/shorva_2.png",
        cost: "25 000",
        type: "Meals-I",
        time: "20 min",
        kkal: "78 kkal",
        bannerColor: 0xffFFC5A8,
        ingCount: 12),
    Meal(
        id: 4,
        name: "Mastava",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/mastava.png",
        cost: "18 000",
        type: "Meals-I",
        time: "15 min",
        kkal: "65 kkal",
        bannerColor: 0xff71C3A1,
        ingCount: 15),
    Meal(
        id: 5,
        name: "Borsh",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/borsh.png",
        cost: "20 000",
        type: "Meals-I",
        time: "15 min",
        kkal: "75 kkal",
        bannerColor: 0xffA8B6FF,
        ingCount: 13),
    Meal(
        id: 6,
        name: "Solyanka",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/solyonka.png",
        cost: "25 000",
        type: "Meals-I",
        time: "15 min",
        kkal: "78 kkal",
        bannerColor: 0xffFFE7A8,
        ingCount: 10),
    Meal(
        id: 7,
        name: "Pelmen",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/pilmen.png",
        cost: "20 000",
        type: "Meals-I",
        time: "15 min",
        kkal: "95 kkal",
        bannerColor: 0xffCEA8FF,
        ingCount: 6),
    Meal(
        id: 8,
        name: "Tovuq lapsha",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/lapsha.png",
        cost: "16 000",
        type: "Meals-I",
        time: "15 min",
        kkal: "75 kkal",
        bannerColor: 0xffA8FFB1,
        ingCount: 7),
    Meal(
        id: 9,
        name: "Teftel",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/teftel.png",
        cost: "25 000",
        type: "Meals-I",
        time: "15 min",
        kkal: "85 kkal",
        bannerColor: 0xffFFA8A8,
        ingCount: 15),
    Meal(
        id: 10,
        name: "Turkish",
        detalis: "Gourmets will appreciate the menu, which includes a fabulous assortment of dishes.The kitchen maintains strict quality control and uses only fresh products from trusted partners, because this is the approach that allows you to create real masterpieces.",
        imageUrl: "assets/dishes/turechiski.png",
        cost: "25 000",
        type: "Meals-I",
        time: "15 min",
        kkal: "85 kkal",
        bannerColor: 0xffF2DFE1,
        ingCount: 9),


  ];
}
